[project]
name = "uv-python-311-test"
version = "0.1.0"
description = "Test code for uv with python 3.11"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dash>=2.16.0",
    "plotly>=5.24.0",
    "coolprop>=6.6.0",
    "numpy>=1.26.0",
    "pandas>=2.2.0",
]
